### ISSUE TITLE
Doesn't work for dictionary containing a dictionary

### ISSUE THREAD

**Issue by nandanathreya** [vinay20045/json-to-csv#19]
First of all, This is great code and I appreciate your effort. This save our days of efforts actually.
Saying that, When I tried for below json file

{"nodes":{"node":[{"rack":"123","state":"KILLED","id":"google:2345","nodeHostName":"dbxcq43ty67q","nodeHTTPAddress":"dbxcq43ty67q:9999","lastHealthUpdate":1522315755208,"version":"2.6.0","healthReport":"healthy","numContainers":52,"usedMemoryMB":98,"availMemoryMB":107520,"usedVirtualCores":4,"availableVirtualCores":30},{"rack":"123","state":"KILLED","id":"google:2345","nodeHostName":"dbxcq43ty67q","nodeHTTPAddress":"dbxcq43ty67q:9999","lastHealthUpdate":1522315755208,"version":"2.6.0","healthReport":"healthy","numContainers":52,"usedMemoryMB":98,"availMemoryMB":107520,"usedVirtualCores":4,"availableVirtualCores":30},{"rack":"123","state":"KILLED","id":"google:2345","nodeHostName":"dbxcq43ty67q","nodeHTTPAddress":"dbxcq43ty67q:9999","lastHealthUpdate":1522315755208,"version":"2.6.0","healthReport":"healthy","numContainers":52,"usedMemoryMB":98,"availMemoryMB":107520,"usedVirtualCores":4,"availableVirtualCores":30}]}}

It didn't work. Actually I had to delete the very first dictionary nodes and then give <'node'> as <namenode>. Please look if you can solve this or if i'm wrong. Correct me.

Thanks bud for everything

**Comment by vinay20045** [comment]
Your understanding is more or less right, but let me clarify...

The script does work as expected, but the output is not usable for data analysis in the sense that the output will just be one big row because of the extra level of encapsulation. Your data looks like...
```
{
    "extra_encapsulation": {
        "node": [
            {
                ...
            },
            ...
        ]
    }
}
```

The script needs a break point (list begin) to start accounting for items to be homogeneous (which could be converted into multiple rows). Therefore, I have designed it to handle the following 2 cases...
```
A list of items with no node, like...
[
    {
        ...
    },
    ...
]
```
or
```
A node encapsulated list of items, like...
{
    "node": [
        {
            ...
        },
        ...
    ]
}
```

So, as you have correctly discovered, you may have to modify your script to remove that extra encapsulation to get the output in a way that is easy to do data analysis.
